28: Hall.csv: none: {'count': 4090, 'truepos': 93, 'falseneg': 11, 'unknownyes': 2, 'falsepos': 393, 'unique': 4090}
28: Hall.csv: three: {'count': 1344, 'truepos': 100, 'falseneg': 2, 'unknownyes': 4, 'falsepos': 17, 'unique': 620}
28: Hall.csv: machine: {'count': 1062, 'truepos': 100, 'falseneg': 2, 'unknownyes': 4, 'falsepos': 13, 'unique': 770}
28: Wahono.csv: none: {'count': 2520, 'truepos': 52, 'falseneg': 8, 'unknownyes': 2, 'falsepos': 222, 'unique': 2520}
28: Wahono.csv: three: {'count': 3643, 'truepos': 60, 'falseneg': 1, 'unknownyes': 1, 'falsepos': 47, 'unique': 1670}
28: Wahono.csv: machine: {'count': 1965, 'truepos': 56, 'falseneg': 3, 'unknownyes': 3, 'falsepos': 20, 'unique': 1490}
28: Danijel.csv: none: {'count': 2640, 'truepos': 43, 'falseneg': 2, 'unknownyes': 3, 'falsepos': 282, 'unique': 2640}
28: Danijel.csv: three: {'count': 2054, 'truepos': 42, 'falseneg': 3, 'unknownyes': 3, 'falsepos': 18, 'unique': 950}
28: Danijel.csv: machine: {'count': 928, 'truepos': 40, 'falseneg': 4, 'unknownyes': 4, 'falsepos': 14, 'unique': 710}
28: K_all3.csv: none: {'count': 540, 'truepos': 38, 'falseneg': 1, 'unknownyes': 6, 'falsepos': 54, 'unique': 540}
28: K_all3.csv: three: {'count': 1040, 'truepos': 34, 'falseneg': 2, 'unknownyes': 9, 'falsepos': 11, 'unique': 470}
28: K_all3.csv: machine: {'count': 721, 'truepos': 26, 'falseneg': 5, 'unknownyes': 14, 'falsepos': 12, 'unique': 620}

------------------------------------------------------------
Sender: LSF System <lsfadmin@n2e1-3>
Subject: Job 213969: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 28> Done

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 28> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2>.
Job was executed on host(s) <2*n2e1-3>, in queue <single_chassis>, as user <zyu9> in cluster <henry2>.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Mon Oct  9 14:05:23 2017
Results reported at Mon Oct  9 19:44:05 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 28
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time   :  22309.72 sec.
    Max Memory :       187 MB
    Max Swap   :      1205 MB

    Max Processes  :         3
    Max Threads    :         8

The output (if any) is above this job summary.



PS:

Read file <./err/28.err.213969> for stderr output of this job.

