7: Hall.csv: none: {'count': 1730, 'truepos': 97, 'falseneg': 6, 'unknownyes': 3, 'falsepos': 90, 'unique': 1730}
7: Hall.csv: three: {'count': 1162, 'truepos': 102, 'falseneg': 0, 'unknownyes': 4, 'falsepos': 4, 'unique': 550}
7: Hall.csv: machine: {'count': 602, 'truepos': 101, 'falseneg': 1, 'unknownyes': 4, 'falsepos': 4, 'unique': 430}
7: Wahono.csv: none: {'count': 2650, 'truepos': 57, 'falseneg': 5, 'unknownyes': 0, 'falsepos': 143, 'unique': 2650}
7: Wahono.csv: three: {'count': 2551, 'truepos': 59, 'falseneg': 0, 'unknownyes': 3, 'falsepos': 6, 'unique': 1210}
7: Wahono.csv: machine: 
------------------------------------------------------------
Sender: LSF System <lsfadmin@n2b1-11>
Subject: Job 244070: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 7> Exited

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 7> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2>.
Job was executed on host(s) <2*n2b1-11>, in queue <single_chassis>, as user <zyu9> in cluster <henry2>.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Thu Oct 12 08:46:58 2017
Results reported at Thu Oct 12 10:18:37 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 7
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :   6603.48 sec.
    Max Memory :       173 MB
    Max Swap   :      1192 MB

    Max Processes  :         3
    Max Threads    :         8

The output (if any) is above this job summary.



PS:

Read file <./err/7.err.244070> for stderr output of this job.

